// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../Fader/dist/component.js', ['DD.ui.Component'], ['DD.ui.EventType', 'DD.ui.renderer.Component', 'goog.ui.Component', 'goog.ui.registry'], false);
goog.addDependency('../../../../Fader/dist/componentrenderer.js', ['DD.ui.renderer.Component'], ['goog.array', 'goog.dom', 'goog.dom.classes', 'goog.style'], false);
goog.addDependency('../../../../Fader/dist/fader.js', ['DD.ui.flickSliders.Fader'], ['DD.ui.flickSliders.FlickSlider', 'DD.ui.flickSliders.renderer.Fader', 'goog.ui.registry'], false);
goog.addDependency('../../../../Fader/dist/flickslider.js', ['DD.ui.flickSliders.FlickSlider'], ['DD.ui.List', 'DD.ui.flickSliders', 'DD.ui.flickSliders.Slide', 'DD.ui.flickSliders.renderer.FlickSlider', 'goog.ui.registry'], false);
goog.addDependency('../../../../Fader/dist/flicksliderrenderer.js', ['DD.ui.flickSliders.renderer.FlickSlider'], ['DD.ui.flickSliders.renderer', 'DD.ui.renderer.Component', 'goog.dom.classes'], false);
goog.addDependency('../../../../Fader/dist/flicksliders.js', ['DD.ui.flickSliders', 'DD.ui.flickSliders.renderer'], [], false);
goog.addDependency('../../../../Fader/dist/list.js', ['DD.ui.List'], ['DD.ui.Component', 'DD.ui.EventType', 'DD.ui.renderer.List', 'goog.array', 'goog.events.Event', 'goog.ui.registry'], false);
goog.addDependency('../../../../Fader/dist/listrenderer.js', ['DD.ui.renderer.List'], ['DD.ui.renderer.Component'], false);
goog.addDependency('../../../../Fader/dist/renderer/faderrenderer.js', ['DD.ui.flickSliders.renderer.Fader'], ['DD.ui.flickSliders.renderer', 'DD.ui.renderer.Component', 'goog.dom.classes'], false);
goog.addDependency('../../../../Fader/dist/slide/renderer/slide.js', ['DD.ui.flickSliders.renderer.Slide'], ['DD.ui.renderer.Component'], false);
goog.addDependency('../../../../Fader/dist/slide/slide.js', ['DD.ui.flickSliders.Slide'], ['DD.ui.Component', 'DD.ui.flickSliders.renderer.Slide', 'goog.ui.registry'], false);
goog.addDependency('../../../../Fader/dist/ui.js', ['DD.ui', 'DD.ui.EventType'], [], false);
